markdown: rdiscount
pygments: true
permalink: /posts/:title
auto: true
rdiscount:
  extensions: [smart]
exclude: [ 'LICENSE', 'Rakefile', 'Gemfile', 'Gemfile.lock' ]

name: Jed Northridge
url: http://jedcn.com
description: Notes
twitter: jedcn
github: jedcn
gravatar_url: https://secure.gravatar.com/avatar/50b6a09b0d1d5d0ba10c4a7ffd828ef8
